# Generated by Django 3.2 on 2023-04-13 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'contracts_suppliers',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('data_allowance', models.IntegerField(default='', max_length=11)),
                ('minutes', models.IntegerField(default='', max_length=11)),
                ('texts', models.IntegerField(default='', max_length=11)),
                ('cost', models.IntegerField(default='', max_length=11)),
                ('pay_interval', models.IntegerField(default='', max_length=11)),
                ('length', models.IntegerField(default='', max_length=11)),
                ('contract_url', models.CharField(default='', max_length=200)),
                ('streetwave_score', models.IntegerField(default='', max_length=11)),
                ('last_update', models.DateTimeField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.contractsuppliers')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_desc', models.CharField(default='', max_length=100)),
                ('bonus_val', models.IntegerField(default='', max_length=11)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.contracts')),
            ],
            options={
                'db_table': 'contracts_bonuses',
            },
        ),
    ]
