# Generated by Django 4.1.7 on 2023-04-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='up_to_date',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
